print("Two vectors of different lengths:")
a=  c(1,3,4,5)
b=  c(6,8,10,20,23)
print(a)
print(b)
result = array(c(a,b),dim = c(3,3,2))
print("New array:")
print(result)
print("The second row of the second matrix of the array:")
print(result[2,,2])
print("The element in the 3rd row and 3rd column of the 1st matrix:")
print(result[3,3,1])
