u=USArrests
#i)a)
str(u)
dim(u)
summary(u)
#b)
torapes<- rowSums(u[, c("Rape"),drop=FALSE])
max_state<-names(which.max(torapes))
print(max_state)
#c)
tomurder<- rowSums(u[, c("Murder"),drop=FALSE])
max_state<-names(which.max(tomurder))
min_state<-names(which.min(tomurder))
print(paste("state with Maximum murder :",max_state))
print(paste("state with Minimum murder :",min_state))